#!/usr/bin/env bash
# Rebuild every unit animation sheet from its kept source render.
#
# Sources: art_sources/sprites/<class>_<state>_src.png — full-resolution
# Codex (GPT image) renders on flat #FF00FF, one row of poses each,
# generated by scripts/art/gen_anim_sheets.py against each class's idle
# frame. Outputs: public/assets/sprites/<class>/<state>.png.
#
# Per-sheet flags are the judgement calls made reviewing each sheet at game
# scale; everything else is the pipeline's defaults (scale from the most
# upright pose, feet on the idle's foot row, legs over the idle's legs):
#   walk          --scale-median: every pose is upright
#   death         --fit: the lying poses are longer than a frame is wide
#   dactyl_rider  the rider-on-mount body measure overshoots; set by eye
#                 against the idle's width
#   boss attack   the first pose holds the greatsword overhead, so the
#                 recovery pose sets the scale
#   shinobi attack every pose is a crouch; nudged down to the idle's size
set -euo pipefail
cd "$(dirname "$0")/../.."
P="python scripts/art/process_anim_sheet.py"
SRC=art_sources/sprites

for c in swordsman spearton knight archer shinobi sentinel dactyl_rider swordmaster boss lenscaster; do
  walk=(); attack=(); hit=()
  case "$c" in
    dactyl_rider) walk=(--body-scale 0.92); attack=(--body-scale 0.87); hit=(--body-scale 0.78) ;;
    boss) attack=(--scale-frame 4) ;;
    shinobi) attack=(--body-scale 0.87) ;;
  esac
  $P "$SRC/${c}_walk_src.png"   "$c" walk 4 --scale-median "${walk[@]}"
  $P "$SRC/${c}_attack_src.png" "$c" attack 5 "${attack[@]}"
  $P "$SRC/${c}_hit_src.png"    "$c" hit 2 "${hit[@]}"
  $P "$SRC/${c}_death_src.png"  "$c" death 4 --fit
done

# Tier 2 (promotion) classes: one character each, idle generated from the
# Tier 1 idle plus the character's portrait, the rest from that new idle
# with the Tier 1 render of each state as a pose guide. The idle has no
# sheet of its own to measure against yet, so it is fitted to its Tier 1
# class's idle (--ref-class); the dactyl king's bigger mount is held to
# the rider's footprint (--ref-scale).
declare -A BASE=( [spearton_lord]=spearton [robinhelm]=archer [shinobi_master]=shinobi
                  [dactyl_king]=dactyl_rider [guardian]=sentinel [prismarch]=lenscaster [khan]=knight )
for c in spearton_lord robinhelm shinobi_master dactyl_king guardian prismarch khan; do
  idle=(); walk=(); attack=(); hit=()
  case "$c" in
    dactyl_king) idle=(--ref-scale 0.9); walk=(--body-scale 0.86); attack=(--body-scale 0.85); hit=(--body-scale 0.88) ;;
  esac
  $P "$SRC/${c}_idle_src.png"   "$c" idle 2 --ref-class "${BASE[$c]}" --scale-median "${idle[@]}"
  $P "$SRC/${c}_walk_src.png"   "$c" walk 4 --scale-median "${walk[@]}"
  $P "$SRC/${c}_attack_src.png" "$c" attack 5 "${attack[@]}"
  $P "$SRC/${c}_hit_src.png"    "$c" hit 2 "${hit[@]}"
  $P "$SRC/${c}_death_src.png"  "$c" death 4 --fit
done

# Bespoke sprites: one named character each (gen_anim_sheets.py BESPOKE) —
# the bosses who all shared the "boss" sheet, and the Ravage's troops.
# Same recipe as Tier 2: the idle fitted to its base class's idle, every
# other state measured against that new idle. Each takes its base class's
# per-state flags (a greatsword boss scales its attack from the recovery
# pose, like "boss").
declare -A BESPOKE=( [nebu]=boss [ndari]=boss [castor]=boss [wren]=shinobi [othren]=knight
                     [serrick]=boss [archbold]=boss [dawn]=boss [herald]=boss [ravage_commander]=boss
                     [ravage_trooper]=swordsman [ravage_lancer]=spearton [ravage_marksman]=archer
                     [bandit_swordsman]=swordsman [bandit_archer]=archer [bandit_spearton]=spearton
                     [royal_guard]=spearton [crown_archer]=archer [kian]=swordsman [rose]=shinobi )
for c in "${!BESPOKE[@]}"; do
  base="${BESPOKE[$c]}"
  idle=(); attack=()
  case "$base" in
    boss) attack=(--scale-frame 4) ;;
    shinobi) attack=(--body-scale 0.87) ;;
  esac
  walk=(); hit=(); death=()
  [ "$c" = ravage_commander ] && idle=(--fit)
  # Othren's idle is measured with his spear upright; his other states
  # came out a size up against it. Set by eye against the knight's sheet.
  [ "$c" = othren ] && { walk=(--body-scale 0.85); attack=(--body-scale 0.9); hit=(--body-scale 0.8); death=(--body-scale 0.9); }
  $P "$SRC/${c}_idle_src.png"   "$c" idle 2 --ref-class "$base" --scale-median "${idle[@]}"
  [ -f "$SRC/${c}_walk_src.png" ]   && $P "$SRC/${c}_walk_src.png"   "$c" walk 4 --scale-median --fit "${walk[@]}"
  [ -f "$SRC/${c}_attack_src.png" ] && $P "$SRC/${c}_attack_src.png" "$c" attack 5 --fit "${attack[@]}"
  [ -f "$SRC/${c}_hit_src.png" ]    && $P "$SRC/${c}_hit_src.png"    "$c" hit 2 --fit "${hit[@]}"
  [ -f "$SRC/${c}_death_src.png" ]  && $P "$SRC/${c}_death_src.png"  "$c" death 4 --fit "${death[@]}"
done
