// Content-hash the streamed assets so their URLs change when their bytes do.
//
// public/ files deploy at STABLE urls (assets/sprites/lenscaster/idle.png)
// and vercel.json gives them a day of browser cache plus a week of
// stale-while-revalidate — the right call for a 440MB streaming set, but it
// means re-dropped art (a portrait retouch, a new sprite sheet) keeps
// serving stale from every returning player's cache for up to a day.
//
// This script writes src/assets/assetVersions.gen.ts mapping each asset
// path to a short md5 of its content. versionedPath() (manifest.ts) appends
// it as ?v=<hash>: a changed file gets a new URL (instant cache miss),
// an unchanged file keeps its exact old URL (cache stays warm).
//
// Runs automatically via the prebuild/pretest hooks in package.json, so
// Vercel regenerates it on every deploy — but commit the refreshed file
// anyway so local tsc agrees with what ships.

import { createHash } from "node:crypto";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(fileURLToPath(new URL(".", import.meta.url)), "..");
const pub = join(root, "public");

const walk = (dir) => {
  const out = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) out.push(...walk(p));
    else if (!e.name.endsWith(".md")) out.push(p);
  }
  return out;
};

const files = ["assets", "audio"].flatMap((d) => {
  try { return walk(join(pub, d)); } catch { return []; }
});

const entries = files
  .map((p) => {
    const key = relative(pub, p).replaceAll("\\", "/");
    const hash = createHash("md5").update(readFileSync(p)).digest("hex").slice(0, 10);
    return [key, hash];
  })
  .sort((a, b) => (a[0] < b[0] ? -1 : 1));

const body = entries.map(([k, h]) => `  ${JSON.stringify(k)}: "${h}"`).join(",\n");
writeFileSync(
  join(root, "src", "assets", "assetVersions.gen.ts"),
  "// AUTO-GENERATED by scripts/hashAssets.mjs — do not edit by hand.\n" +
  "// Regenerate after dropping/replacing art: node scripts/hashAssets.mjs\n" +
  "// (the prebuild/pretest npm hooks run it for you.)\n" +
  "export const ASSET_VERSIONS: Record<string, string> = {\n" + body + "\n};\n"
);
console.log(`assetVersions.gen.ts: ${entries.length} files hashed`);
